---
title: "Tournaments"
author: "Greg, Josie, Zach, Ryan"
format: html
editor: visual
---

Llull (1283) 

Kendall and Smith (1940): Judges makes consistent preferences.  

Slater's I (1961): Measure of inconsistency

Thurstone Mosteller model (1928): Bradley Terry Model with a normal CDF transformation.  

Kendall-Wei (1952)
Elo (1978)
Glicko (1998) and Glicko2 (2006?): Essentially Bayesian Elo.  
Trueskill (2006): Used in halo 2 or 3.    

 
Weak stochastic probablity. $P(A \rightarrow B) > 0.5$  and $P(B \rightarrow C) > 0.5$ then $P(A \rightarrow C) > 0.5$.  

CRSP: Chain Rock Scissor Paper.  Non transitive model.  


Ratings vs rankings: Ratings are numeric estimates of strengths.  Rankings are a function of ratings.  

Let's start with what a BAD tournament would be.  

Quarto manuscript template:https://github.com/mikemahoney218/quarto-arxiv

##Papers 

https://www.sciencedirect.com/science/article/pii/S0378375803003215
"Maximum weight perfect match problem"

## Deterministic Binary Outcome Tournaments

 - Knockout (KO) lKO
  - 1KO
  - 2KO
      - True 3rd, college wrestling, repechage
  - 3KO
  - Seeding issues,.  

 - nRR 
  - 1RR
  - 2RR
  - partial RR
  
## Dynamic Binary Outcome Tournaments 

  - Swiss
  - Dynamic Knockout (reseeding after every round)

    
  

  

  

## Tournaments

 - Single elimination (NCAA tournament, NFL playoffs)
  - Seeding issues (Tennis: https://www.liveabout.com/definition-of-seeding-3207821)
   Reseeding after each round.  Straight knockout.  
  - Second faces Third for silver medal.  Guarantees than sivler has 1 loss and bronze has 2 losses.  
  - With a 3rd place match (Badminton: https://www.nbcolympics.com/news/badminton-101-olympic-competition-format)
  - Single elimination with series (NBA, MLB, NHL)
  - Ladder tournaments (Korean baseball does best of 3 with one team starting up 1-0 in the opening round)
  - Seeding issues (NFL re-seeds, NCAA tournament straight bracket)
  - Group/Pool play followed by knockout stages (World Cup, Euro, Overwatch World CUp. )
  
 - Double elimination (Overwatch Champions League)
  - Repechage (Olympic Wrestling, Tae Kwon Do, Judo) (These also aware 2 bronze medals)
  - True Double elimination
  - Double elimination but a single loss before finals means you can onyl go for third place (College wrestling)
  
  - Triple Elimination (Curling! https://thegrandslamofcurling.com/bracketology-101-triple-knockout-explained-2021/)
 
 - Swiss Tournament (https://en.chessbase.com/post/125-years-swiss-system)

 - Round Robin
  - Single and Double.  
  - Baseball is an imbalanced multiple round robin qualifying round. 
  
  - https://www.tandfonline.com/doi/abs/10.1080/01621459.1952.10501178
  
 - Waterfall format
   - Introduced in the Smash 64 community, [they claim](https://thesmashwriter.wordpress.com/2017/04/24/what-is-a-waterfall-bracket/)
   - Recent example was [Super Smash Con 2023](https://www.start.gg/tournament/super-smash-con-2023/event/64-1v1-singles/overview)
    - Players are seeded $1 \rightarrow n$ and grouped into $k$ divisions, 1 best, $n$ and $k$ worst. 
    - The worst $\frac{n + \epsilon}{k}$ play in [relatively small round robin pools](https://www.start.gg/tournament/super-smash-con-2023/event/64-1v1-singles/brackets/1184919/1833431). Some fraction advance. In this linked example, There are 16 pools in division 4, where each pool is roughly 13 players, with 4 from each division advancing. 
    - The advancing players are then entered into pools with the slightly better-seeded players, and again complete round robins. This iterates over and over again. In this example, to make the numbers work, there are also [wildcard rounds](https://www.start.gg/tournament/super-smash-con-2023/event/64-1v1-singles/brackets/1184927/1833460) to advance an extra few players to further divisions. 
    - In Smash 64, this ultimately leads to a top 16 or 32, which then becomes a double-elimination tournament (all prior losses are ignored). The [top 32](https://www.start.gg/tournament/super-smash-con-2023/event/64-1v1-singles/brackets/1184923/1833456) is seeded by the [top division pool results](https://www.start.gg/tournament/super-smash-con-2023/event/64-1v1-singles/brackets/1184922/1833451). 
  
 
 - Heat based events (Track 5000m and below, swimming) 
 
 - Ranking Round followed by single elimination (Olympic Archery https://www.nbcolympics.com/news/archery-101-olympic-competition-format-and-scoring)
 
 - Elimination racing (Cycling, Bachelor/Bachelorette, Survivor)
 
 Tournament: a series of contests between a number of competitors, who compete for an overall prize. Oxford Dictionary
  Wiki: "A tournament is a competition involving at least three competitors, all participating in a sport or game"

Tournament (graphy theory): [wikipedia definition](https://en.wikipedia.org/wiki/Tournament_(graph_theory)) and in [McShane (2019)](https://scholar.smu.edu/hum_sci_statisticalscience_etds/13/) -- essentially a "round robin tournament" -- a graph where every node (competitor: A, B, C) is connected by a directed edge (win A -> B or lose A <- B), where there are no loops (self-directed edges -- competitors cannot play against themselves). AKA a complete directed graph with no loops; has $n$ nodes and $\choose{n}{2}$ edges. John W. Moon's [Topic on Tournaments](https://www.gutenberg.org/ebooks/42833) is the classic graph theoretical tournaments text. This definition should be used to disambiguate _tournament_, especially since graph theory may be used. 


 
 (https://www.espn.com/olympics/story/_/id/40536088/2024-paris-summer-olympics-track-field-medaling-format-rules)
 
 
Curling and DOE! https://khazna.ku.ac.ae/en/publications/applying-design-of-experiments-tooptimize-the-performance-level-o

Poker: https://arxiv.org/abs/physics/0703122

Graph Theory Stuff: 
Chickens: https://link.springer.com/article/10.1007/BF02476378


Are elections tournaments?  

Tournament of Tournaments.  


 - aggregation of rankings (golf fedex cup, formula one, tour de france)




https://liquipedia.net/overwatch/Overwatch_Champions_Series/2024/North_America/Stage_2
Swiss, Top Cut Swiss, Group play then a double elimiation bracket!

https://www.vgcguide.com/swiss-and-top-cut





```{r}
results <- data.frame(h = c("i","i","j","i","j","l"), a = c("j","l","l","k","k","k"), hpoints = c(3,3,3,1,1,1), apoints = c(0,0,0,1,1,1))
                
library(tidyverse)     
h <-results %>% group_by(h) %>% summarize(sum = sum(hpoints))  
a <- results %>% group_by(a) %>% summarize(sum = sum(apoints)) 
names(a) <- c("h","sum")
d <- rbind(h,a)
d %>% group_by(h) %>%  summarize(sum = sum(sum))  %>% arrange(-sum)

#Now reverse the outcomes
results <- data.frame(h = c("i","i","j","i","j","l"), a = c("j","l","l","k","k","k"), hpoints = c(0,0,0,1,1,1), apoints = c(3,3,3,1,1,1))
                
library(tidyverse)     
h <-results %>% group_by(h) %>% summarize(sum = sum(hpoints))  
a <- results %>% group_by(a) %>% summarize(sum = sum(apoints)) 
names(a) <- c("h","sum")
d <- rbind(h,a)
d %>% group_by(h) %>%  summarize(sum = sum(sum))  %>%arrange(-sum)


                 
                     
```


Note for Greg: 
Can we build a simulator that computes the probability of a team winning in two steps: 1) the team strength comes from a distribution itself and then the actual outcome come from flipping a coin based on the particular draw of the distribtuion.  

Can we model a sport and how muhc variability it has?  So like estimate the probability of rteam A beating team B as a function of relative strengths but also use that other distribution to model the variability of the sport.  Does this exist?  

